package entity;
// Generated May 24, 2022 11:48:49 PM by Hibernate Tools 4.3.1



/**
 * Dosen generated by hbm2java
 */
public class Dosen  implements java.io.Serializable {


     private String nid;
     private String namaDs;

    public Dosen() {
    }

    public Dosen(String nid, String namaDs) {
       this.nid = nid;
       this.namaDs = namaDs;
    }
   
    public String getNid() {
        return this.nid;
    }
    
    public void setNid(String nid) {
        this.nid = nid;
    }
    public String getNamaDs() {
        return this.namaDs;
    }
    
    public void setNamaDs(String namaDs) {
        this.namaDs = namaDs;
    }
    
    public String findNamaDs(String nmdosen) {
        return this.namaDs;
    }



}


