package entity;
// Generated Nov 18, 2021 9:43:58 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import org.hibernate.Session;
import org.hibernate.Transaction;
import util.Alats;




/**
 * Dosen generated by hbm2java
 */
public class Dosen  implements java.io.Serializable {


     private String nid;
     private String namaDs;

    public Dosen() {
    }

    public Dosen(String nid, String namaDs) {
       this.nid = nid;
       this.namaDs = namaDs;
    }
   
    public String getNid() {
        return this.nid;
    }
    
    public void setNid(String nid) {
        this.nid = nid;
    }
    public String getNamaDs() {
        return this.namaDs;
    }
    
    public void setNamaDs(String namaDs) {
        this.namaDs = namaDs;
    }
public static List<Dosen> read() {
    List<Dosen> a = new ArrayList<Dosen>();
    Transaction tran = null;
    Session session = Alats.getSessionFactory().openSession();
    try {
        tran = session.beginTransaction();
        a = session.createQuery("from Dosen").list();
    } catch (RuntimeException e) {
        e.printStackTrace();
    } finally {
        session.flush();
        session.close();
    }
    return a;
}



}


