package entity;
// Generated Nov 18, 2021 9:43:58 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import org.hibernate.Session;
import org.hibernate.Transaction;
import util.Alats;




/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private String nim;
     private String namaMh;
     private String kodeMk;

    public Mahasiswa() {
    }

    public Mahasiswa(String nim, String namaMh, String kodeMk) {
       this.nim = nim;
       this.namaMh = namaMh;
       this.kodeMk = kodeMk;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public String getNamaMh() {
        return this.namaMh;
    }
    
    public void setNamaMh(String namaMh) {
        this.namaMh = namaMh;
    }
    public String getKodeMk() {
        return this.kodeMk;
    }
    
    public void setKodeMk(String kodeMk) {
        this.kodeMk = kodeMk;
    }




}


