package entity_genap;
// Generated Jul 2, 2022 9:50:38 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GenapMahasiswa generated by hbm2java
 */
public class GenapMahasiswa  implements java.io.Serializable {


     private int nim;
     private String namaMhs;
     private Date tanggalLahir;
     private String mataKuliah;

    public GenapMahasiswa() {
    }

    public GenapMahasiswa(int nim, String namaMhs, Date tanggalLahir, String mataKuliah) {
       this.nim = nim;
       this.namaMhs = namaMhs;
       this.tanggalLahir = tanggalLahir;
       this.mataKuliah = mataKuliah;
    }
   
    public int getNim() {
        return this.nim;
    }
    
    public void setNim(int nim) {
        this.nim = nim;
    }
    public String getNamaMhs() {
        return this.namaMhs;
    }
    
    public void setNamaMhs(String namaMhs) {
        this.namaMhs = namaMhs;
    }
    public Date getTanggalLahir() {
        return this.tanggalLahir;
    }
    
    public void setTanggalLahir(Date tanggalLahir) {
        this.tanggalLahir = tanggalLahir;
    }
    public String getMataKuliah() {
        return this.mataKuliah;
    }
    
    public void setMataKuliah(String mataKuliah) {
        this.mataKuliah = mataKuliah;
    }




}


